GET http://localhost:3000/posts
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODgwNDY4MDEsImV4cCI6MTY4ODA0NjgxNn0.30z2kb1EXokPkIPPGUplyUaff9LjqWdee6rmFZcTm_U
Content-Type: application/json

{
    "query": "ha"
}

###
POST http://localhost:4000/signup
Content-Type: application/json

{
    "username" : "Pesho",
    "password" : "123456",
    "email": "mrgoblings@gmail.com",
    "displayName": "XXpeshoXX"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywidXNlck5hbWUiOiJwZXNobyIsImlhdCI6MTY4Nzk4MjQ1N30.0Ai8K0JqGc3tkuR2XfK5jMnoUSvzkSyJRXzaI5fWK7k"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Pesho", 
    "password": "123456" 
}


###
GET  http://localhost:3000/posts

